[package]

name = "sarosa"
version = "0.0.1"
authors = ["The GreenPix developers"]
build = "build.rs"

[dependencies]
# oil = "*"
log = "*"
env_logger = "*"
docopt = "0.6.*"
rustc-serialize = "0.3"

[dependencies.sarosa_engine]
path = "./sarosa_engine"
version = "=0.0.1"
